services:
  - type: web
    name: pfc-stockflow
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn estoque_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PFC.settings